GET http://localhost:8080/owner/docs/tree?id=141
Accept: application/json

###
POST http://localhost:8080/add-document
Content-Type: application/json

{}

###
POST http://localhost:8080/
Content-Type: application/json

{
  "name": "mock project-name",
  "description": "it's great project"
}

###

POST http://localhost:8080/add-document
Content-Type: application/json

{
  "title": "mack document",
  "description": "mock description",
  "repoUrl": "https://github.com/excellent-cancer/perishing-constraint.git",
  "projectId": "111"
}

###

GET http://127.0.0.1:8080/owner/docs?pages=1&count=10
Content-Type: application/json


